# 服务端口
server:
  port: 1000

spring:
  # 数据库配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.229.78.80:3306/mashup?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wangzherongyao
    initialize: false
